image: node:16

stages:
  - lint
  - test

lint:
  tags:
    - hva
  stage: lint
  script:
    - npm install --force
    - npm run check

test:
  tags:
    - hva
  stage: test
  script:
    - npm install --force
    - echo "Setting environment variable for TEST_MODE"
    - echo "TEST_MODE=true" >> .env
    - npm test